# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
before:
  hooks:
    - go mod download
project_name: aws-cct
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ignore:
      - goos: darwin
        goarch: 386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Brew formula'
brews:
- tap:
    owner: rgoomar
    name: aws-cct
  description: AWS Cost Comparison Tool
  homepage: https://github.com/rgoomar/aws-cct
  license: "MIT"
  test: |
    system "#{bin}/aws-cct --help"
