# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsCct < Formula
  desc "AWS Cost Comparison Tool"
  homepage "https://github.com/rgoomar/aws-cct"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rgoomar/aws-cct/releases/download/v2.0.0/aws-cct_2.0.0_darwin_arm64.tar.gz"
      sha256 "c824bee52f1063101bfe8d20d1c73ba569a395fe1b0ab99f9facc2afec4cec40"

      def install
        bin.install "aws-cct"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rgoomar/aws-cct/releases/download/v2.0.0/aws-cct_2.0.0_darwin_amd64.tar.gz"
      sha256 "f85254ff619702bc6c18463a6adfbaa70fc62fc7dadf2a3e53814eee87cb6160"

      def install
        bin.install "aws-cct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgoomar/aws-cct/releases/download/v2.0.0/aws-cct_2.0.0_linux_arm64.tar.gz"
      sha256 "483afdc557ef41a1e839d2d4fc4933b09618cc95ee738b3de923ec567af52349"

      def install
        bin.install "aws-cct"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rgoomar/aws-cct/releases/download/v2.0.0/aws-cct_2.0.0_linux_amd64.tar.gz"
      sha256 "fd684217167896237dbb7bd4362eac757ca3d8c2ddddbf79fcc5f79c45c132c8"

      def install
        bin.install "aws-cct"
      end
    end
  end

  test do
    system "#{bin}/aws-cct --help"
  end
end
