# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsCct < Formula
  desc "AWS Cost Comparison Tool"
  homepage "https://github.com/rgoomar/aws-cct"
  version "2.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rgoomar/aws-cct/releases/download/v2.2.4/aws-cct_Darwin_x86_64.tar.gz"
      sha256 "813242173b30d47617185e296dab3a2aee664e5770402bd015af1bd685e1f2e6"

      def install
        bin.install "aws-cct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rgoomar/aws-cct/releases/download/v2.2.4/aws-cct_Darwin_arm64.tar.gz"
      sha256 "646f338ffc71b7bceed380b3036adbbf1805944cfd7221e56d9de9b788d9c9b4"

      def install
        bin.install "aws-cct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rgoomar/aws-cct/releases/download/v2.2.4/aws-cct_Linux_x86_64.tar.gz"
        sha256 "0a938530446d2d2f30237cd1920b48e60bc6f3d85e96d8cd1796db8ce6a00fc5"

        def install
          bin.install "aws-cct"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rgoomar/aws-cct/releases/download/v2.2.4/aws-cct_Linux_arm64.tar.gz"
        sha256 "34e5e00def90b34031b1cbece917fc7d2c8b9ab8313ca0a9bef9d94911ef24d9"

        def install
          bin.install "aws-cct"
        end
      end
    end
  end

  test do
    system "#{bin}/aws-cct --help"
  end
end
